import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Layout/Sidebar";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import Providers from "./providers";
import MobileSidebar from "@/components/Layout/MobileSidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <Header />
          <div className="flex">
            <div className="m-4 hidden md:block">
              <Sidebar />
            </div>
            <div className="m-4 flex-1">{children}</div>
          </div>
          <div className="mx-4 mt-4 mb-18 md:mb-4">
            <Footer />
          </div>

          <MobileSidebar />
        </Providers>
      </body>
    </html>
  );
}
