import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Layout/Sidebar";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import Providers from "./providers";
import MobileSidebar from "@/components/Layout/MobileSidebar";
import { Locale } from "@/i18n/request";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} className="h-full" suppressHydrationWarning>
      <body className={`${poppins.variable} h-full antialiased`}>
        <Providers>
          <div className="flex h-full">
            <main className="flex h-full w-full flex-col">
              <Header />
              <div className="flex flex-1 flex-col overflow-y-auto pb-14 md:pb-0">
                <div className="flex">
                  <div className="m-4 hidden md:block">
                    <Sidebar />
                  </div>
                  <div className="m-4 flex-1">{children}</div>
                </div>
                <div className="m-4">
                  <Footer />
                </div>
              </div>
            </main>
            <MobileSidebar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
